version: '3'
services:
  go-gin:
    container_name: go-gin
    restart: always
    image: eilinge/go-gin:latest
    ports:
      - "8080:8080"
    
networks:
  default:
    external:
      name: my-network
