apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-workflow-role
rules:
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflows/status", "workflows/finalizers", "workflowtaskresults", "eventsources"]
  verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
- apiGroups: [""]
  resources: ["pods", "pods/log", "services"]
  verbs: ["get", "list", "watch","create", "update", "delete", "patch"]
- apiGroups: ["*"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch","create", "update", "delete", "patch"]
