apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
    name: github
spec:
    template:
        serviceAccountName: operate-workflow-sa
    dependencies:
        - name: test-dep
          eventSourceName: github
          eventName: example
          filters:
              data:
                  # Type of Github event that triggered the delivery: [pull, push, issues, label, ...]
                  # https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads
                  - path: headers.X-Github-Event
                    type: string
                    value:
                        - push
                  - path: body.ref
                    type: string
                    value:
                        - master
                        - "refs/heads/master"
    triggers:
        - template:
              name: github-workflow-trigger
              argoWorkflow:
                  operation: resubmit  # resubmit argo workflow
                  source:
                      resource:
                          apiVersion: argoproj.io/v1alpha1
                          kind: Workflow
                          metadata:
                              name: buildkit-gogin-dwf29 # workflow name exists in argo workflow
          retryStrategy:
              steps: 3
