apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-gin
  namespace: dev
  labels:
    app: go-gin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-gin
  template:
    metadata:
      labels:
        app: go-gin
    spec:
      containers:
      - image: eilinge/go-gin:v1.0
        name: go-gin
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: go-gin
  namespace: dev
  labels:
    app: go-gin
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: go-gin
  type: ClusterIP
